Chimpagne/ChimpagneApp

.idea/gradle.xml
.idea/misc.xml
app/build.gradle.kts
build.gradle.kts

Google Map API Added

---

build.gradle.kts

gradle update

---

.github/workflows/ci.yml
app/build.gradle.kts
build.gradle.kts
gradle/libs.versions.toml

Migrate all dependencies in the clean libs.versions.toml file to make Sonar happy

Version Catalog

---

app/src/main/java/com/monkeyteam/chimpagne/MainActivity.kt
app/src/main/java/com/monkeyteam/chimpagne/ui/FindAnEventScreen.kt
app/src/main/java/com/monkeyteam/chimpagne/ui/HomeScreen.kt
app/src/main/java/com/monkeyteam/chimpagne/ui/navigation/NavigationActions.kt
app/src/main/java/com/monkeyteam/chimpagne/ui/utilities/SpinnerView.kt
app/src/main/java/com/monkeyteam/chimpagne/ui/viewmodel/AuthViewModel.kt

I added the authentication view model to jump straight to the main screen if already logged in

authenticaton view model

---

app/src/androidTest/java/com/monkeyteam/chimpagne/EventCreationScreenTest.kt
app/src/main/java/com/monkeyteam/chimpagne/MainActivity.kt
app/src/main/java/com/monkeyteam/chimpagne/ui/EventCreationScreen.kt
app/src/main/java/com/monkeyteam/chimpagne/ui/HomeScreen.kt
app/src/main/java/com/monkeyteam/chimpagne/ui/navigation/NavigationActions.kt

The user can go the the event creation screen from the home screen, click on the buttons to navigate between panels, and enter some basic informations.

Event creation screen: Initial UI setup and testing

---

app/src/androidTest/java/com/monkeyteam/chimpagne/EventCreationScreenTest.kt
app/src/main/java/com/monkeyteam/chimpagne/ui/EventCreationScreen.kt
app/src/main/java/com/monkeyteam/chimpagne/ui/HomeScreen.kt
app/src/main/res/values-fr/strings.xml
app/src/main/res/values/strings.xml

Translations done for the event creation screen

Translations

---

app/src/androidTest/java/com/monkeyteam/chimpagne/EventCreationScreenTest.kt
app/src/main/java/com/monkeyteam/chimpagne/MainActivity.kt
app/src/main/java/com/monkeyteam/chimpagne/ui/EventCreationScreen.kt
app/src/main/java/com/monkeyteam/chimpagne/ui/components/Button.kt

Setup of the UI component
It's already used in EventCreationTest and his tests.
Changed EventCreationScreen to have a default parameter value, according to this comment https://github.com/Chimpagne/ChimpagneApp/pull/58#pullrequestreview-1983486283

GoBackButton component

---

app/src/androidTest/java/com/monkeyteam/chimpagne/AccountTests.kt
app/src/main/java/com/monkeyteam/chimpagne/ui/AccountCreationScreen.kt
app/src/main/java/com/monkeyteam/chimpagne/ui/AccountEditScreen.kt

Fixed AccountTests to run and disabled profile picture change, because its still bugged.

Fix account tests

---

app/src/androidTest/java/com/monkeyteam/chimpagne/AccountTests.kt
app/src/main/java/com/monkeyteam/chimpagne/MainActivity.kt
app/src/main/java/com/monkeyteam/chimpagne/model/database/ChimpagneAccount.kt
app/src/main/java/com/monkeyteam/chimpagne/ui/AccountCreationScreen.kt
app/src/main/java/com/monkeyteam/chimpagne/ui/AccountEditScreen.kt
app/src/main/java/com/monkeyteam/chimpagne/ui/AccountSettingsScreen.kt
app/src/main/java/com/monkeyteam/chimpagne/ui/navigation/NavigationActions.kt
app/src/main/java/com/monkeyteam/chimpagne/ui/utilities/AccountUtilities.kt
app/src/main/java/com/monkeyteam/chimpagne/viewmodels/AccountViewModel.kt

The logout button is now working. I also refactored some part of the AccountViewModel to make it easier to reason about.
Note: the android back button isn't working well with the different account screens and the logout button but at least the button is working.

Logout button

---

app/build.gradle.kts
app/src/androidTest/java/com/monkeyteam/chimpagne/MapTest.kt
app/src/androidTest/java/com/monkeyteam/chimpagne/smallClassesUITest.kt
app/src/main/java/com/monkeyteam/chimpagne/ui/LoginScreen.kt
app/src/main/java/com/monkeyteam/chimpagne/ui/components/DateSelector.kt
app/src/main/java/com/monkeyteam/chimpagne/ui/utilities/GoogleUtilities.kt
app/src/main/java/com/monkeyteam/chimpagne/ui/utilities/MapContainer.kt
app/src/main/res/values-fr/strings.xml
app/src/main/res/values/strings.xml
app/src/test/java/com/monkeyteam/chimpagne/smallClassesTest.kt
gradle/libs.versions.toml

Some UI Tests where possible have been added and small adjustment to work with the tests have also been made to classes.

Added UI tests

---

app/build.gradle.kts
app/src/androidTest/java/com/monkeyteam/chimpagne/AccountSystemTests.kt
app/src/androidTest/java/com/monkeyteam/chimpagne/AccountViewModelTests.kt
app/src/androidTest/java/com/monkeyteam/chimpagne/FindEventScreenTest.kt
app/src/androidTest/java/com/monkeyteam/chimpagne/accounts/AccountSystemTests.kt
app/src/androidTest/java/com/monkeyteam/chimpagne/accounts/AccountTests.kt
app/src/main/java/com/monkeyteam/chimpagne/MainActivity.kt
app/src/main/java/com/monkeyteam/chimpagne/model/database/ChimpagneAccount.kt
app/src/main/java/com/monkeyteam/chimpagne/model/database/ChimpagneAccountManager.kt
app/src/main/java/com/monkeyteam/chimpagne/model/database/ChimpagneEventManager.kt
app/src/main/java/com/monkeyteam/chimpagne/model/database/Database.kt
app/src/main/java/com/monkeyteam/chimpagne/ui/AccountCreationScreen.kt
app/src/main/java/com/monkeyteam/chimpagne/ui/AccountEditScreen.kt
app/src/main/java/com/monkeyteam/chimpagne/ui/AccountSettingsScreen.kt
app/src/main/java/com/monkeyteam/chimpagne/ui/LoginScreen.kt
app/src/main/java/com/monkeyteam/chimpagne/ui/navigation/NavigationActions.kt
app/src/main/java/com/monkeyteam/chimpagne/ui/utilities/AccountUtilities.kt
app/src/main/java/com/monkeyteam/chimpagne/ui/utilities/GoogleUtilities.kt
app/src/main/java/com/monkeyteam/chimpagne/viewmodels/AccountViewModel.kt
gradle/libs.versions.toml

This pull request refactors the account system and adds the ability to add pictures to your account.
- Toasts have been added to let users know what they need to fill in when creating an account + for feedback when an account is created or updated.
- The image can be selected from your images on your phone and is then stored on the firebase storage (link as reference is stored in ChimpagneAccount.
- Also merged the changes of @QuicheLorraine3600 pr: #89 
**Important: Old accounts on firebase have to be deleted after this is merged to match new format of accounts!**

Image selection

---

app/src/main/java/com/monkeyteam/chimpagne/ui/components/Button.kt

You can add an optional parameter to the Chimpagne Button to add an Icon to the left of it

Added Icon for Chimpagne Button

---

app/src/androidTest/java/com/monkeyteam/chimpagne/FindEventScreenTest.kt
app/src/main/java/com/monkeyteam/chimpagne/ui/FindEventScreen.kt

Added a few tests for the FindEventScreen

Writing more tests

---

app/src/androidTest/java/com/monkeyteam/chimpagne/FindEventScreenTest.kt

database had to be added as an argument to the viewModels in the tests

fixed main

---

app/src/androidTest/java/com/monkeyteam/chimpagne/EventCreationScreenTest.kt
app/src/androidTest/java/com/monkeyteam/chimpagne/FindEventScreenTest.kt
app/src/androidTest/java/com/monkeyteam/chimpagne/LocationTests.kt
app/src/androidTest/java/com/monkeyteam/chimpagne/MapTest.kt
app/src/androidTest/java/com/monkeyteam/chimpagne/newtests/ui/account/AccountCreationUITest.kt
app/src/androidTest/java/com/monkeyteam/chimpagne/newtests/ui/account/AccountEditUITest.kt
app/src/androidTest/java/com/monkeyteam/chimpagne/newtests/viewmodels/FindEventViewModelTests.kt
app/src/main/java/com/monkeyteam/chimpagne/model/database/ChimpagneAccountManager.kt
app/src/main/java/com/monkeyteam/chimpagne/model/database/ChimpagneEventManager.kt
app/src/main/java/com/monkeyteam/chimpagne/model/database/ChimpagneRoles.kt
app/src/main/java/com/monkeyteam/chimpagne/model/location/Nominatim.kt
app/src/main/java/com/monkeyteam/chimpagne/ui/components/LocationSelector.kt
app/src/main/java/com/monkeyteam/chimpagne/ui/utilities/MapContainer.kt
app/src/main/java/com/monkeyteam/chimpagne/viewmodels/FindEventsViewModel.kt

did ktfmt formating on Main

---

app/src/androidTest/java/com/monkeyteam/chimpagne/LocationSelectorTest.kt
app/src/main/java/com/monkeyteam/chimpagne/ui/components/LocationSelector.kt

I have managed to remove the search bar when not needed and only show it to display the results of the search. Also I have added some basic tests for the locationSelector component.

Location bar

---

.github/workflows/ci.yml
app/src/androidTest/java/com/monkeyteam/chimpagne/newtests/TestUtils.kt
app/src/androidTest/java/com/monkeyteam/chimpagne/newtests/model/event/JoinEventTests.kt
app/src/androidTest/java/com/monkeyteam/chimpagne/newtests/ui/ViewDetailEventScreenTests.kt
app/src/androidTest/java/com/monkeyteam/chimpagne/newtests/viewmodels/EventViewModelTests.kt
app/src/androidTest/java/com/monkeyteam/chimpagne/newtests/viewmodels/FindEventViewModelTests.kt
app/src/main/java/com/monkeyteam/chimpagne/ui/EventCreationScreen.kt
app/src/main/java/com/monkeyteam/chimpagne/viewmodels/EventViewModel.kt
app/src/main/java/com/monkeyteam/chimpagne/viewmodels/FindEventsViewModel.kt

This PR is meant:
-  to fix old view model tests that don't work 100% of the time due to the database changes.
- to add new view model tests to add coverage.
- to fix CI that runs 2 times and modify the database simultaneously which caused errors.

Fix + add new view model tests

---

app/src/main/java/com/monkeyteam/chimpagne/ui/AccountEditScreen.kt
app/src/main/java/com/monkeyteam/chimpagne/ui/AccountSettingsScreen.kt
app/src/main/java/com/monkeyteam/chimpagne/ui/utilities/AccountUtilities.kt

Fixed the bug where the Icon was clickable in the settings screen and the save changes button in the editAccountScreen.

Fix 2 bugs

---

app/src/androidTest/java/com/monkeyteam/chimpagne/newtests/ui/event/EditEventScreenTest.kt
app/src/androidTest/java/com/monkeyteam/chimpagne/newtests/ui/event/EventCreationScreenTest.kt
app/src/main/java/com/monkeyteam/chimpagne/model/database/ChimpagneEventManager.kt
app/src/main/java/com/monkeyteam/chimpagne/ui/event/EditEventScreen.kt
app/src/main/res/values-fr/strings.xml
app/src/main/res/values/strings.xml
app/src/test/java/com/monkeyteam/chimpagne/ChimpagneSupplyTest.kt

To make the app more robust, some basic checks were also added to the database manager.
The tests helped discover some inconsistencies regarding null safety, an issue has been filled.

More testing for Edit Event

---

app/src/main/res/values-fr/strings.xml
app/src/main/res/values/strings.xml

Fixing the capitalization/typos for the french text, removed some unused strings

french typos fixed, removed unused strings

---

app/src/main/java/com/monkeyteam/chimpagne/model/database/ChimpagneEvent.kt
app/src/test/java/com/monkeyteam/chimpagne/model/ChimpagneEventTest.kt

In order to avoid to do "listOf(ownerId) + staffList() + guestList()" everywhere to get the list of all the users associated with an event, I just created a method for it: ChimpagneEvent.userSet(). That's it.

ChimpagneEvent.userSet()

---

app/src/main/java/com/monkeyteam/chimpagne/model/database/ChimpagneEvent.kt
app/src/main/java/com/monkeyteam/chimpagne/ui/components/SocialMedia.kt
app/src/main/java/com/monkeyteam/chimpagne/viewmodels/EventViewModel.kt

Issue #178  from @QuicheLorraine3600

Issue (too many fields in database) addressed

---

app/src/androidTest/java/com/monkeyteam/chimpagne/newtests/model/event/EventTest.kt
app/src/androidTest/java/com/monkeyteam/chimpagne/newtests/viewmodels/EventViewModelTests.kt
app/src/main/java/com/monkeyteam/chimpagne/model/database/AtomicChimpagneEventManager.kt
app/src/main/java/com/monkeyteam/chimpagne/model/database/ChimpagneEvent.kt
app/src/main/java/com/monkeyteam/chimpagne/model/database/ChimpagnePoll.kt
app/src/main/java/com/monkeyteam/chimpagne/viewmodels/EventViewModel.kt

This PR is meant to:
- add a poll data class for an event poll which contains an id, a title, a query and a list of options that users can vote on and a map mapping users to the option they voted on.  
- add database functions to add / delete a poll, vote an option on a poll.
- add event view model functions to add / delete a poll, vote an option on a poll.
- add robust tests for all of the above functionality.

Polls and voting database and view model functionality

---

app/src/androidTest/java/com/monkeyteam/chimpagne/MapTest.kt
app/src/main/java/com/monkeyteam/chimpagne/ui/utilities/ChimpagneClustering.kt
app/src/main/java/com/monkeyteam/chimpagne/ui/utilities/MapContainer.kt
app/src/test/java/com/monkeyteam/chimpagne/ZoomTest.kt

- `ChimpagneClustering` moved to UI/Utilities folder : [issue](https://github.com/Chimpagne/ChimpagneApp/issues/132)
- Added a separate ZoomTest and deleted the comments

Issues fixes for Arnaud

---

app/src/androidTest/java/com/monkeyteam/chimpagne/HomescreenTest.kt
app/src/main/java/com/monkeyteam/chimpagne/model/location/Location.kt
app/src/main/java/com/monkeyteam/chimpagne/ui/HomeScreen.kt
app/src/main/java/com/monkeyteam/chimpagne/ui/components/LocationIconTextButton.kt
app/src/main/java/com/monkeyteam/chimpagne/viewmodels/FindEventsViewModel.kt
app/src/main/res/values-fr/strings.xml
app/src/main/res/values/strings.xml

Several improvements, As discussed in the issue https://github.com/Chimpagne/ChimpagneApp/issues/198:
- The feed filters out the necessary events
- There is a way for the user to enable the GPS directly from the app, refreshing the feed accordingly
https://github.com/Chimpagne/ChimpagneApp/assets/29517376/8e440920-0544-4511-9791-3d6520e4d4ae

the feed now works properly

---

app/src/androidTest/java/com/monkeyteam/chimpagne/newtests/ui/components/DateRangeSelectorUITests.kt
app/src/main/java/com/monkeyteam/chimpagne/ui/components/DateRangeSelector.kt

Turns this
into this
using a BottomSheet instead of a Dialog.

fix of DateRangeSelector

---

app/src/main/java/com/monkeyteam/chimpagne/ui/FindEventScreen.kt
app/src/main/java/com/monkeyteam/chimpagne/ui/components/TagField.kt

This pull request addresses the 2 issues addressed in #188 and #213 . I have decided to only create one PR for this because they are both tiny changes.

fixed 2 issues

---

app/src/main/java/com/monkeyteam/chimpagne/ui/event/polls/CreatePollDialog.kt
app/src/main/java/com/monkeyteam/chimpagne/ui/event/polls/PollAndVotingScreen.kt
app/src/main/res/values-fr/strings.xml
app/src/main/res/values/strings.xml

This PR is meant to do the requested changes in this PR: #236, as it was merged without my consent:
- removed magic values.
- replace the term popup by dialog.
- fixed some French translations.

Did requested changes for Polls UI screens 

---

app/src/androidTest/java/com/monkeyteam/chimpagne/newtests/ui/event/WeatherCarouselTest.kt

This test has been pushed on main but is broken. This PR just fixes this issue by deleting it.

remove testWeatherAppWithOldEvent

---

app/src/androidTest/java/com/monkeyteam/chimpagne/newtests/ui/ViewDetailEventScreenTests.kt
app/src/main/java/com/monkeyteam/chimpagne/ui/HomeScreen.kt
app/src/main/java/com/monkeyteam/chimpagne/ui/components/eventview/EventActions.kt
app/src/main/res/values-fr/strings.xml
app/src/main/res/values/strings.xml

This PR is meant to bring back the missing delete event button that was on the event screen. 
It must have been delete when the refactoring happened.

Added back delete event button
