Chimpagne/ChimpagneApp

app/build.gradle.kts, app/src/androidTest/java/com/monkeyteam/chimpagne/EventCreationScreenTest.kt, app/src/androidTest/java/com/monkeyteam/chimpagne/LocationSelectorTests.kt, app/src/androidTest/java/com/monkeyteam/chimpagne/LocationTests.kt, app/src/main/AndroidManifest.xml, app/src/main/java/com/monkeyteam/chimpagne/model/location/Nominatim.kt, app/src/main/java/com/monkeyteam/chimpagne/ui/components/LocationSelector.kt, app/src/main/res/xml/network_security_config.xml, gradle/libs.versions.toml
I've refined the geolocation features within `Nominatim.kt` and `LocationSelector.kt` to enhance user interaction and data presentation. The LazyColumn now neatly displays up to five search results, each distinctly bounded for improved clarity. Addressing the JSON response variability was a significant challenge, as the returned data's format could vary widely based on the user's query. There was no straightforward, all-encompassing method to selectively display only the relevant attributes since they might or might not be present in the response from the Nominatim API. However, I devised tailored solutions for different scenarios, leading to a codebase that's not only more readable but also more maintainable. Additionally, I've implemented a feature for easy clearing of the location …
=> geolocation updated

.github/workflows/ci.yml
As you might have noticed, on a pull request, the CI is launched 2 times. This not only slows down tests but also can break them because of database concurrency issues. This simple PR solves this issue by launching the CI only one time.
This
becomes
=> Double CI fix

app/src/androidTest/java/com/monkeyteam/chimpagne/EventCreationScreenTest.kt, app/src/main/java/com/monkeyteam/chimpagne/model/database/ChimpagneEventManager.kt, app/src/main/java/com/monkeyteam/chimpagne/viewmodels/EventViewModel.kt
This PR aims to solve an issue in the way we create and edit events with ChimpagneEventManager and EventViewModel. 
Before, the method buildChimpagneEvent of EventViewModel assumed the ownerId of the event would be added by the Database. While it worked well, it made impossible to get the ownerId of the event from the UI layer.
I solved this issue by adding a ownerId field to EventUIState. At the creation of the ViewModel, if eventID is null (i.e. you are creating the event), this field is set to the UID of the current logged account.
=> EventViewModel: auto add ownerId on buildChimpagneEvent()

app/src/androidTest/java/com/monkeyteam/chimpagne/newtests/ui/ViewDetailEventScreenTests.kt, app/src/main/java/com/monkeyteam/chimpagne/MainActivity.kt, app/src/main/java/com/monkeyteam/chimpagne/ui/MyEventsScreen.kt, app/src/main/java/com/monkeyteam/chimpagne/ui/ViewDetailEventScreen.kt, app/src/main/java/com/monkeyteam/chimpagne/viewmodels/EventViewModel.kt, app/src/main/java/com/monkeyteam/chimpagne/viewmodels/MyEventsViewModel.kt
This PR is meant to fix issue like the one described here: https://github.com/Chimpagne/ChimpagneApp/issues/119 where the UI elements don't update correctly because the view model is being cached and is not fetching the newer information from the database.
The proposed solution here are that now all fetch style functions of view models are made public so that ~the UI can call them when the screen is created / recreated~ we call them when navigation to that screen.
=> Fixed issue #119

app/src/androidTest/java/com/monkeyteam/chimpagne/newtests/TestUtils.kt, app/src/androidTest/java/com/monkeyteam/chimpagne/newtests/viewmodels/EventViewModelTests.kt, app/src/androidTest/java/com/monkeyteam/chimpagne/newtests/viewmodels/MyEventsViewModelTests.kt
This PR is meant to fix issue #157: 
Where doing multiple firebase requests sometimes don't work making some tests fail.
To fix this I added delays to separate each requests so that they can be done correctly.
I also fixed some other inconsistencies with the view model tests such as the way you log into an account.
=> time is merely a construct, fix issue #157

app/src/androidTest/java/com/monkeyteam/chimpagne/newtests/model/event/EventTest.kt, app/src/androidTest/java/com/monkeyteam/chimpagne/newtests/model/event/JoinEventTests.kt, app/src/main/java/com/monkeyteam/chimpagne/model/database/AtomicChimpagneEventManager.kt, app/src/main/java/com/monkeyteam/chimpagne/model/database/ChimpagneAccountManager.kt, app/src/main/java/com/monkeyteam/chimpagne/model/database/ChimpagneEventManager.kt
This PR solves an important concurrency issue happening if multiple devices are displaying and interacting with the same event using the power of atom !
More seriously, you can now access ChimpagneEventManager methods said "atomic" (i.e. methods that update only one field instead of rewriting an entire object) using `ChimpagneEventManager.atomic.<method name>` . Please use those methods to interact with events that are already created and on the database.
=> ☢ Atom protects us from race conditions ⚛

app/src/androidTest/java/com/monkeyteam/chimpagne/newtests/viewmodels/AccountViewModelTests.kt, app/src/main/java/com/monkeyteam/chimpagne/viewmodels/AccountViewModel.kt
This PR adds the method `fetchAccounts` the AccountViewModel. It takes a list of `ChimpagneAccountUID` as parameter and stores the result of the request in `uiStage.value.fetchedAccounts` as a `Map<ChimpagneAccountUID, ChimpagneAccount>`. Use this method in the NavGraph of MainActivity when the UID of a `ChimpagneAccount` isn't sufficient for your screen.
=> AccountViewModel.fetchAccounts

app/src/main/java/com/monkeyteam/chimpagne/ui/AccountCreationScreen.kt, app/src/main/java/com/monkeyteam/chimpagne/ui/navigation/NavigationActions.kt
This PR finally fixes our NavGraph ! Now it *really* goes back to the previous screen. The issue was in the `navigateTo` method of `NavigationActions`. Also when you have finished your account creation, you cannot go back to the AccountCreationScreen.
=> Navgraph fix

app/src/main/java/com/monkeyteam/chimpagne/model/database/AtomicChimpagneAccountManager.kt, app/src/main/java/com/monkeyteam/chimpagne/model/database/ChimpagneAccountManager.kt, app/src/main/java/com/monkeyteam/chimpagne/model/database/ChimpagneEventManager.kt
This PR just fixes issue #164: when an event is deleted, the event reference is removed from the `joinedEvent` field of all the entries in the "accounts" table so we don't have any "ghost" events.
=> Leave event on event deletion

app/src/androidTest/java/com/monkeyteam/chimpagne/newtests/ui/event/EditEventScreenTest.kt, app/src/androidTest/java/com/monkeyteam/chimpagne/newtests/ui/event/EventCreationScreenTest.kt, app/src/main/java/com/monkeyteam/chimpagne/ui/event/AdvancedLogisticsPanel.kt, app/src/main/java/com/monkeyteam/chimpagne/ui/event/EditEventScreen.kt, app/src/main/java/com/monkeyteam/chimpagne/ui/event/EventCreationScreen.kt, app/src/main/java/com/monkeyteam/chimpagne/ui/event/FirstPanel.kt, app/src/main/java/com/monkeyteam/chimpagne/ui/event/PanelBars.kt, app/src/main/java/com/monkeyteam/chimpagne/ui/event/SuppliesPanel.kt, app/src/main/res/values-fr/strings.xml, app/src/main/res/values/strings.xml
This PR is meant to fix inconsistencies in the Create and Edit event screen:
- Notably issue #166 where the top bars of both screens are misaligned and the text is small.
- The first panel is now scrollable, which fixes the issue where the description can get so long that the lower buttons disappear and are no longer reachable.
- All titles in panels now have icons and the text is of the same size to remain consistent with the first 2 panels.
- All mentions of groceries have been swapped with supplies.
- Panel's top and bottom bars are now in a separate file as they are a shared element for both screens, which removes some code duplication.
=> Fixed inconsistencies in Create and Edit Event

app/src/androidTest/java/com/monkeyteam/chimpagne/newtests/viewmodels/EventViewModelTests.kt, app/src/main/java/com/monkeyteam/chimpagne/viewmodels/EventViewModel.kt
This PR adds atomic methods to update / remove and assign / unassign a supply to the EventViewModel. This will be useful for the Supply Screen (future PR). Those methods are "atomic" in the sense that they do not rewrite the entire event in the database. The changes are made "directly" and do not require a call to updateTheEvent() to take effect.
=> EventViewModel: add atomical supply methods

app/src/androidTest/java/com/monkeyteam/chimpagne/newtests/TestUtils.kt, app/src/androidTest/java/com/monkeyteam/chimpagne/newtests/ui/event/supplies/SuppliesScreenUITests.kt, app/src/androidTest/java/com/monkeyteam/chimpagne/newtests/ui/event/supplies/SupplyDialogsUITests.kt, app/src/androidTest/java/com/monkeyteam/chimpagne/newtests/ui/event/supplies/SupplyScreenComponentsUITests.kt, app/src/main/java/com/monkeyteam/chimpagne/MainActivity.kt, app/src/main/java/com/monkeyteam/chimpagne/ui/ViewDetailEventScreen.kt, app/src/main/java/com/monkeyteam/chimpagne/ui/event/details/supplies/EditSupplyDialog.kt, app/src/main/java/com/monkeyteam/chimpagne/ui/event/details/supplies/GuestSupplyDialog.kt, app/src/main/java/com/monkeyteam/chimpagne/ui/event/details/supplies/StaffSupplyDialog.kt, app/src/main/java/com/monkeyteam/chimpagne/ui/event/details/supplies/SuppliesScreen.kt, app/src/main/java/com/monkeyteam/chimpagne/ui/event/details/supplies/SupplyCard.kt, app/src/main/java/com/monkeyteam/chimpagne/ui/event/details/supplies/SupplyDialogAccountEntry.kt, app/src/main/java/com/monkeyteam/chimpagne/ui/navigation/NavigationActions.kt, app/src/main/java/com/monkeyteam/chimpagne/viewmodels/EventViewModel.kt, app/src/main/res/values-fr/strings.xml, app/src/main/res/values/strings.xml
This PR adds the supplies screen to the detailed event page. From there, if you're a staff, you can add / edit / delte / assign supplies. As a guest, you can only assign / unassign yourself from a supply.
A new route (SUPPLIES_SCREEN) has been added.
Here are some screens:
- Staff perspective
- Guest perspective
=> Supplies Screen

app/src/main/java/com/monkeyteam/chimpagne/ui/ViewDetailEventScreen.kt
This PR is meant to fix a merge that took out the navigate part of view detail of event page to the supplies page.
It was probably overlooked in the reviews since a lot of deletions happened in the file in [this PR](https://github.com/Chimpagne/ChimpagneApp/pull/187) .
=> Fix supplies in main

app/src/androidTest/java/com/monkeyteam/chimpagne/newtests/model/event/QueryFiltersTests.kt, app/src/androidTest/java/com/monkeyteam/chimpagne/newtests/ui/components/DateRangeSelectorUITests.kt, app/src/androidTest/java/com/monkeyteam/chimpagne/newtests/viewmodels/FindEventViewModelTests.kt, app/src/main/java/com/monkeyteam/chimpagne/model/database/QueryFilters.kt, app/src/main/java/com/monkeyteam/chimpagne/model/utils/DateTools.kt, app/src/main/java/com/monkeyteam/chimpagne/ui/FindEventScreen.kt, app/src/main/java/com/monkeyteam/chimpagne/ui/components/CustomDialog.kt, app/src/main/java/com/monkeyteam/chimpagne/ui/components/DateRangeSelector.kt, app/src/main/java/com/monkeyteam/chimpagne/viewmodels/FindEventsViewModel.kt, app/src/main/res/values-fr/strings.xml, app/src/main/res/values/strings.xml
This PR adds the ability to select a date range (not just a date) on the Discover Event screen.
This component is very similate to DateSelector but offers the ability to select a range instead of a single date. 
You cannot select past dates (I didn't see where it could be useful in our project).
`happensInDateRangeFilter` takes 2 date instead of one. `happensOnThisDateFilter` has been removed as it should not be used anymore in our project. If you *really* want to have something similar, just call  `happensInDateRangeFilter(day, day)`
I removed the `selectedDate` field of this view model to replace with `startDate` and `endDate`. The method `updateSelectedDate` has been replaced with `updateDateRange` accordingly.
=> Date range selection on Discover Events screen

app/src/androidTest/java/com/monkeyteam/chimpagne/newtests/ui/event/EditEventScreenTest.kt, app/src/androidTest/java/com/monkeyteam/chimpagne/newtests/ui/event/EventCreationScreenTest.kt, app/src/androidTest/java/com/monkeyteam/chimpagne/newtests/viewmodels/EventViewModelTests.kt, app/src/main/java/com/monkeyteam/chimpagne/ui/event/AdvancedLogisticsPanel.kt, app/src/main/java/com/monkeyteam/chimpagne/ui/event/ChooseSocialsPanel.kt, app/src/main/java/com/monkeyteam/chimpagne/ui/event/EventCreationScreen.kt, app/src/main/java/com/monkeyteam/chimpagne/ui/event/PanelBars.kt, app/src/main/java/com/monkeyteam/chimpagne/ui/event/SuppliesPanel.kt, app/src/main/java/com/monkeyteam/chimpagne/ui/event/TagsAndPubPanel.kt, app/src/main/java/com/monkeyteam/chimpagne/viewmodels/EventViewModel.kt, app/src/main/java/com/monkeyteam/chimpagne/viewmodels/FindEventsViewModel.kt, app/src/main/res/values-fr/strings.xml, app/src/main/res/values/strings.xml
Bug fixes:
- No negative values for the number of beds and parking spaces
- Checks if the title is empty and displays a toast if necessary
- Checks if the start and end date are equals, or if the start is later than the end, displays a toast if necessary
See the related issue : https://github.com/Chimpagne/ChimpagneApp/issues/192
This required some changes to the viewmodel for event creation.
"Advanced logistics" has been renammed to "Accomodations"
=> Event creation improvements

app/src/main/java/com/monkeyteam/chimpagne/viewmodels/AccountViewModel.kt
The merge with #207 broke testAccountUpdateScreen. This PR fixes this issue by reverting this change:
=> Fix testAccountUpdateScreen

app/src/main/java/com/monkeyteam/chimpagne/viewmodels/EventViewModel.kt
Bug fixed: If you logout and login of your account, you can't create an event anymore, because the ui state is loading as a default. This fixes this
=> Fix Bug EventViewModel

app/src/main/java/com/monkeyteam/chimpagne/model/database/ChimpagneEvent.kt, app/src/main/java/com/monkeyteam/chimpagne/model/database/ChimpagneEventManager.kt, app/src/main/java/com/monkeyteam/chimpagne/model/database/Database.kt, app/src/main/java/com/monkeyteam/chimpagne/ui/EventScreen.kt, app/src/main/java/com/monkeyteam/chimpagne/ui/components/EventCard.kt, app/src/main/java/com/monkeyteam/chimpagne/ui/components/ImageLoader.kt, app/src/main/java/com/monkeyteam/chimpagne/ui/components/eventview/ImageCard.kt, app/src/main/java/com/monkeyteam/chimpagne/ui/event/AdditionalFeaturesPanel.kt, app/src/main/java/com/monkeyteam/chimpagne/ui/event/EditEventScreen.kt, app/src/main/java/com/monkeyteam/chimpagne/ui/event/EventCreationScreen.kt, app/src/main/java/com/monkeyteam/chimpagne/viewmodels/EventViewModel.kt, app/src/main/java/com/monkeyteam/chimpagne/viewmodels/FindEventsViewModel.kt, app/src/main/res/values-fr/strings.xml, app/src/main/res/values/strings.xml
This PR adds the ability to have user chosen pictures for events. The user is able to choose a picture for their event in the EventCreationScreen and edit it later on in the EditEventScreen. The picture then gets displayed on all the ImageCards (everywhere the picture was before).
Specific Changes:
- AdvancedLogisticsPanel has been made AdditionalFeaturesPanel, where the picture is able to be chosen.
- The eventViewModel now also has a field for tempImageUri, when the image has been chosen but not yet saved in the editScreen. As well as new functions to support the storing and retrieving of the image (built into fetch).
- ImageLoader had to been changed, because the old way of doing it had a bug with my new implementation, that just displayed a grey screen when the imageUri was null.
- …
=> Event Picture

app/src/main/java/com/monkeyteam/chimpagne/ui/components/eventview/OrganiserView.kt
This PR aims to integrate Android's Share Sheet in the EventScreen.kt file (see: https://developer.android.com/training/sharing/send) for easier sharing of events.) This resolves Issue #205 
We had mentioned in our discussions that we wanted it to be clear that the event link is copied to the clipboard (adding a Chimpagne Toast), however, I believe a toast is not necessary anymore because with the Android Share Sheet there is a by default toast now. Note that this does not show on the emulator for clipboard accessibility issues (see the video below to see how it works on an android phone)
https://github.com/Chimpagne/ChimpagneApp/assets/60262512/b2114197-5ef0-49e9-b112-b85758e0ce99
=> Android Share Sheet

app/src/androidTest/java/com/monkeyteam/chimpagne/FindEventScreenTest.kt, app/src/androidTest/java/com/monkeyteam/chimpagne/newtests/ui/ManageStaffScreenTests.kt, app/src/androidTest/java/com/monkeyteam/chimpagne/newtests/ui/MyEventsScreenTests.kt, app/src/androidTest/java/com/monkeyteam/chimpagne/newtests/ui/PollsAndVotingScreenTests.kt, app/src/androidTest/java/com/monkeyteam/chimpagne/newtests/ui/ViewDetailEventScreenTests.kt, app/src/main/java/com/monkeyteam/chimpagne/ui/EventScreen.kt, app/src/main/java/com/monkeyteam/chimpagne/ui/ManageStaffScreen.kt, app/src/main/java/com/monkeyteam/chimpagne/ui/MyEventsScreen.kt, app/src/main/java/com/monkeyteam/chimpagne/ui/components/Button.kt, app/src/main/java/com/monkeyteam/chimpagne/ui/components/TopBar.kt, app/src/main/java/com/monkeyteam/chimpagne/ui/event/EditEventScreen.kt, app/src/main/java/com/monkeyteam/chimpagne/ui/event/EventCreationScreen.kt, app/src/main/java/com/monkeyteam/chimpagne/ui/event/details/supplies/SuppliesScreen.kt, app/src/main/java/com/monkeyteam/chimpagne/ui/event/polls/PollAndVotingScreen.kt
This PR aims to bring more consistency within the app: 
- the usage of TopAppBar has been replaced by our custom TopBar in all the app
- screens not yet using our GoBackButton have been updated
- the deprecated version of GoBackButton has been removed
- tests have been updated accordingly
=> Consistent use of the TopBar and GoBackButton components

app/src/main/java/com/monkeyteam/chimpagne/model/database/ChimpagneEventManager.kt, app/src/main/java/com/monkeyteam/chimpagne/ui/DetailScreenSheet.kt, app/src/main/java/com/monkeyteam/chimpagne/ui/HomeScreen.kt, app/src/main/java/com/monkeyteam/chimpagne/ui/MyEventsScreen.kt, app/src/main/java/com/monkeyteam/chimpagne/ui/event/SuppliesPanel.kt, app/src/main/java/com/monkeyteam/chimpagne/ui/event/details/supplies/SuppliesScreen.kt
This PR is meant to fix:
- issue #204, where now when creating a new supplies they appear on top of the displayed supplies. You can see this change from the create event screen (3rd panel) or from the supplies screen for an existing event.
- issue #129, where now when fetching events, they are always ordered by date. You can see this change from the MyEvents screen or in the FindEvents screen bottom sheet.
=> fixed ordering issues

app/src/main/java/com/monkeyteam/chimpagne/model/database/ChimpagneAccountManager.kt
My first PR for delete account: #238 didn't delete the picture of the user from the database. This is fixed in here
=> Delete Profile Picture, when deleting Account

app/src/androidTest/java/com/monkeyteam/chimpagne/end2end/EventCreation.kt, app/src/androidTest/java/com/monkeyteam/chimpagne/newtests/viewmodels/EventViewModelTests.kt, app/src/main/java/com/monkeyteam/chimpagne/ui/components/LocationSelector.kt, app/src/main/java/com/monkeyteam/chimpagne/viewmodels/EventViewModel.kt, app/src/main/res/values-fr/strings.xml, app/src/main/res/values/strings.xml
I have fixed issue #243 . Now users are obligated to enter a location when editing/creating events. I needed to modify the end2end test "EventCreation" because it was failing due to the fixed issue.
=> Resolve Issue #243 (Location Should be mandatory when creating/Editing) an event

app/src/main/java/com/monkeyteam/chimpagne/ui/components/LocationSelector.kt
When editing an event, the previous location was not shown in the search field. This is now fixed
Before:
https://github.com/Chimpagne/ChimpagneApp/assets/79521990/eeb626e3-8f39-43df-a045-e5ba063188cb
After:
https://github.com/Chimpagne/ChimpagneApp/assets/79521990/690ffbfb-35cd-4081-93de-13d35d2a7af5
=> previous location now displayed when editing event
